name: Recipe Binder
favicon: null
layout_spectrum: 0.1710526
typography_spectrum: 0.3189223
title: Recipe Binder
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8872181
  lightness: 0
  saturation: 0.231203
  rhythmicContrast: 0.2380952
purpose: []
