name: Recipe Binder
favicon: null
layout_spectrum: 0.1710526
typography_spectrum: 0.3189223
title: Recipe Binder
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c5c4c2'
    - '#201911'
    - '#7a4813'
    - '#fefdff'
    - '#ba9348'
  brandStrength: 0.9375
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
